### ISSUE TITLE
Schematics for Player

### ISSUE THREAD

**Issue by m4p** [ttsiodras/ATtiny85_MonkeyIslandPlayer#1]
Would you be able to share the schematics for the final player? (Components and wiring)
Thanks so much!

**Comment by ttsiodras** [comment]
Hi Martin.

It's so simple I am afraid I didn't even draw one... :-)
 
The only part that matters is the transistor-speaker connection - which [my blog post](https://www.thanassis.space/monkeyisland.html) contains - just scroll down until you see it.

For the rest, as you can see [at the top of the code](https://github.com/ttsiodras/ATtiny85_MonkeyIslandPlayer/blob/master/beeperJukeboxTiny.ino#L1)...

- The transistor's base to PB0 (via the 1K resistor)
- The LED to PB1 (via a 220Ohm resistor)
- ...and the pushbutton to PB3.

The pushbutton pin is pulled to GND via a 10K resistor, but pulled up to VCC when the button is pushed.
  
ASCII-art of the ATtiny85:

```
                                       +--------+
          (PCINT5/~RESET/ADC0/dW) PB5  | 1    8 | VCC
   (PCINT3/XTAL1/CLKI/~OC1B/ADC3) PB3  | 2    7 | PB2 (SCK/USCK/SCL/ADC1/T0/INT0/PCINT2)
    (PCINT4/XTAL2/CLKO/OC1B/ADC2) PB4  | 3    6 | PB1 (MISO/DO/AIN1/OC0B/OC1A/PCINT1)
                                  GND  | 4    5 | PB0 (MOSI/DI/SDA/AIN0/OC0A/~OC1A/AREF/PCINT0)
                                       +--------+

```

**Comment by m4p** [comment]
ah. I missed the one at the top of the code! thanks for pointing me to it.

**Comment by ttsiodras** [comment]
I'll add all this to the README, maybe more people will ask for it.

Thx!
